//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FinshJor
//  @ File Name : StaticData.cpp
//  @ Date : 2017/9/28
//  @ Author : hefeng
//
//


#include "StaticData.h"

StaticData StaticData::sharedStaticData() {
	//获取StaticData类的单件对象。
	static StaticData* g_sharedStaticData=NULL;


	return g_sharedStaticData;
}

bool StaticData::init() {
	//将plist文件中的数据导入到内存中，并由_dictionary来操作该部分的数据
	_dictionary=CCDictionary::createWithContentsOfFile(_staticFileName.c_str());
	_dictionary->retain();

	return true;
}

const char* StaticData::stringFromKey(:string key std) {
	//从_dictionary中key对应的值类型为字符串，则可以通过该函数获取到该key对应的值。
	//cocos2d::CCString
	return _dictionary->valueFormKey(key)->getCString();
}

int StaticData::intFromKey(:string key std) {
	//从_dictionary中key对应的值类型为整形
	//cocos2d::CCString
	return _dictionary->valueForKey(key)-> intValue ();
}

float StaticData::floatFromKey(:string key std) {
	//从_dictionary中key对应的值类型为浮点型
	//cocos2d::CCString
	return _dictionary->valueForKey(key)-> floatValue ();
}

bool StaticData::booleanFromKey(:string key std) {
	//从_dictionary中key对应的值的类型为布尔型
	//cocos2d::CCString
	return _dictionary->valueForKey(key)-> boolValue ();
}

cocos2d::CCPoint StaticData::pointFromKey(std::string key) {
	//从_dictionary中key对应的值类型是用来表示一个点的坐标
	//cocos2d::CCString
	return _dictionary->valueForKey(key)-> getCString ();

}

cocos2d::CCRect StaticData::rectFromKey(std::string  key) {


	return _dictionary->rectForKey(key)-> getCString ();
}

cocos2d::CCSize StaticData::sizeFromKey(std::string key) {


	return _dictionary->sizeForKey(key)-> getCString ();
}

void StaticData::purge() {
	CC_SAFE_RELEASE_NULL(g_sharedStaticData);
}

StaticData::StaticData() {

}

StaticData::~StaticData() {

}

