//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FinshJor
//  @ File Name : StaticData.h
//  @ Date : 2017/9/28
//  @ Author : hefeng
//
//


#if !defined(_STATICDATA_H)
#define _STATICDATA_H


class StaticData {
public:
	cocos2d::CCDictionary* _dictionary;
	std::string* _staticDataPath;
	static StaticData sharedStaticData();
	bool init();
	const char* stringFromKey(:string key std);
	int intFromKey(:string key std);
	float floatFromKey(:string key std);
	bool booleanFromKey(:string key std);
	cocos2d::CCPoint pointFromKey(std::string key);
	cocos2d::CCRect rectFromKey(std::string  key);
	cocos2d::CCSize sizeFromKey(std::string key);
	static void purge();
private:
	StaticData();
	~StaticData();
};

#endif  //_STATICDATA_H
