//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FinshJor
//  @ File Name : StaticData.cpp
//  @ Date : 2017/9/28
//  @ Author : hefeng
//
//


#include "StaticData.h"

StaticData StaticData::sharedStaticData() {

}

bool StaticData::init() {

}

const char* StaticData::stringFromKey(:string key std) {

}

int StaticData::intFromKey(:string key std) {

}

float StaticData::floatFromKey(:string key std) {

}

bool StaticData::booleanFromKey(:string key std) {

}

cocos2d::CCPoint StaticData::pointFromKey(std::string key) {

}

cocos2d::CCRect StaticData::rectFromKey(std::string  key) {

}

cocos2d::CCSize StaticData::sizeFromKey(std::string key) {

}

void StaticData::purge() {

}

StaticData::StaticData() {

}

StaticData::~StaticData() {

}

